### ISSUE TITLE
Setting `Insert` keyboard shortcut for "Add child and start edit" doesn't work and cannot be set back to `Tab` afterwards

### ISSUE THREAD

**Issue by Arakade** [raydac/netbeans-mmd-plugin#100]
When I set the `Insert` key for "Add child and start edit" then use on a node, no child is created.  (Insert is the key used in FreeMind by default so I'd hoped to not relearn that shortcut.)
Realising the problem I press the "Edit code" button to try to set the shortcut back to `Tab` but that moves the input focus back to "Edit code"!  (without setting the shortcut!)
Next I thought to just type in "Tab" and while I _can_ delete the text from the "Key code" input area, I then cannot type in it!

Thanks for an otherwise very handy mind-mapping tool!  (I know bug reports can come across all whiny so I hoped to give a little positive to balance 😉)

**Comment by raydac** [comment]
you can try [1.5.2-SNAPSHOT](https://github.com/raydac/netbeans-mmd-plugin/releases/tag/1.5.2-S)
