### ISSUE TITLE
Add flatlaf support

### ISSUE THREAD

**Issue by BenHerbst** [raydac/netbeans-mmd-plugin#104]
Skia reto is really good application, but misses a good theme in my opinion.
That is why flatlaf would be a good solution, also to get a dark mode.

**Comment by raydac** [comment]
very good idea, thanks
I have added support of FlatLaf into snapshot, you can take a look at

**Comment by BenHerbst** [comment]
![grafik](https://user-images.githubusercontent.com/83538916/178571714-e913f3a1-882f-400b-9d1d-35977e104653.png)
Wow, it looks very good.
I use Scia Reto mainly only for mind map and do Plantuml in Doom emacs, but you could maybe also add dark theme / Flatlaf support for the text area. I will replace Minder now with Scia reto. Thank you so much for this awesome mind map app!
