### ISSUE TITLE
How to remove jump between nodes ?

### ISSUE THREAD

**Issue by Ribosome2** [raydac/netbeans-mmd-plugin#113]
I create jump between node be holding CTRL and drap node A to node B ,But How to remove them ?(Inside JetBrain IDEA)
I can't find any releated content in FAQ and ducumentation

**Comment by raydac** [comment]
select "Edit jump" for jump source topic and there press menu button "Select none"

**Comment by Ribosome2** [comment]
> select "Edit jump" for jump source topic and there press menu button "Select none"

Thanks ,I missed that .
