### ISSUE TITLE
IntellijIDEA, improve editor font support

### ISSUE THREAD

**Issue by Mori-hub** [raydac/netbeans-mmd-plugin#120]
Please provide support languages by encoding="utf-8"
<img width="896" alt="image" src="https://github.com/raydac/netbeans-mmd-plugin/assets/53067774/28d9a94d-295c-4a7c-8b17-a25db2b7c24b">

**Comment by raydac** [comment]
it uses UTF8 internally, are you sure that selected Font supports charset in MMD file?

**Comment by Mori-hub** [comment]
I use IDEA MIND Map version 1.6.5
in Android Studio Iguana | 2023.2.1 Canary 18
I checked the font is Tahoma

**Comment by raydac** [comment]
could you make some example of mind map with such non-readable topics and attach it to the issue?

**Comment by Mori-hub** [comment]
[Loan Finder.zip](https://github.com/raydac/netbeans-mmd-plugin/files/13691977/Loan.Finder.zip)
 Yes, please see this file. (.mm)

**Comment by raydac** [comment]
ok, now I see the issue, I will improve work with font render, as workaround you can change current mind map topic font to a standard one like Arial
![image](https://github.com/raydac/netbeans-mmd-plugin/assets/3008810/3ad153f9-0a54-457c-80b5-a1e24208aad9)

**Comment by Mori-hub** [comment]
Thank you

**Comment by raydac** [comment]
so if you want use Farsi then select font supporting the char-set in "Mind map topic text font" and Note editor for topic records uses IDE editor font and if the font doesn't support Farsi then select appropriate font in Settings->Editor->Font
