### ISSUE TITLE
Searching for nodes

### ISSUE THREAD

**Issue by netmackan** [raydac/netbeans-mmd-plugin#15]
It would be nice if one could search the topic names. This could be useful for larger mind maps.

The search could either be in the MindMapPanel or in the Navigator or both.

Searches in the Navigator would preferably work the same way as in the Projects window where if I start typing a search bar is opened at the bottom of the view and while I type it starts selecting any matching node. As a user was expecting it to work the same for the Navigator window.

**Comment by raydac** [comment]
it is no so easy because it should be integrated with two very different API provided by Idea and NetBeans

**Comment by raydac** [comment]
search function added since 1.4.4
