### ISSUE TITLE
Context menu only opens by mouse click

### ISSUE THREAD

**Issue by netmackan** [raydac/netbeans-mmd-plugin#16]
Way to reproduce:
1. Select a node in the graph, for instance by clicking Ctrl+Space
2. Click Shift+F10 (on Linux systems where this should open the context menu, or using the context menu button if such exists on the keyboard)
Expected: The popup menu that you otherwise would get by right clicking on the node should be opened.
Actual: No popup is displayed

In my system Shift+F10 works in other applications including other parts of NetBeans IDE.

Having a look at the code it seems to menu is displayed manually as a result of the mouse events instead of using the JComponent.setComponentPopupMenu() which might register the possibly system-dependent bindings etc. Not sure if it would be possible to use that one though.

**Comment by raydac** [comment]
since 1.2.0 it is possible to open popup context menu with key combination

**Comment by netmackan** [comment]
Thank you, works great!
