### ISSUE TITLE
Добавить в сущность (узел) атрибут Priority

### ISSUE THREAD

**Issue by Hoseyn76** [raydac/netbeans-mmd-plugin#2]
Добавить в сущность (узел) атрибут Priority.

В соответсвии с матрицей Эйзенхауэра достаточно 4 приоритета.
При отображении надо отображать и цифрой и цветом.

**Comment by raydac** [comment]
начиная с 1.2.0 появился Plugin API и можно теперь реализовывать разную требуемую специфическую функциональность самостоятельно
