### ISSUE TITLE
i have installed the full version netbeans-8.1_linux.sh

### ISSUE THREAD

**Issue by NootanR** [raydac/netbeans-mmd-plugin#21]
not all modules are enabled,standard module :org,i am getting 6 errors of this type.
tried reinstasll ,doesn't open..

**Comment by raydac** [comment]
could you describe the issue in more informative way? which IDE and OS do you use? could you provide text or screenshot of the error?

**Comment by raydac** [comment]
I have tried to install ubuntu 15.10 and NB full from .sh file with OpenJDK 1.7, after that I have installed NB MindMap plugin and it works, I saw some errors related to communication of NB and its inside plugins with OpenJDK but they are not related to NB MindMap plugin
could you make a screenshot of error behaviour which you have?

**Comment by raydac** [comment]
can't reproduce the issue
