### ISSUE TITLE
cant enter shift+enter on mac

### ISSUE THREAD

**Issue by gpeach-mdlive** [raydac/netbeans-mmd-plugin#22]
having trouble inserting returns in mind map text.  I would normally do this with shift+enter but no luck is there a different key combination?

**Comment by raydac** [comment]
only shft+enter is hardcoded for text editor, the combination inserts the "next line char" into topic text, what is your OS and IDE?

**Comment by raydac** [comment]
I have added the key short-cut into into list of short-cuts and since 1.2.1 it will be possible to tune the key combination, the default one is SHIFT+ENTER
