### ISSUE TITLE
Export to Org Mode

### ISSUE THREAD

**Issue by roshanq** [raydac/netbeans-mmd-plugin#24]
There has never been a better match between this and the org mode.

Please add this feature

**Comment by raydac** [comment]
I have implemented export into Org Mode format, take a look pls and check that it is correct if you use the format, I don't use Org Mode and don't know how to check and can be wrong in exporting, if you find any error then report and I will fix that

**Comment by roshanq** [comment]
Thanks for the quick update. 

How do i package the new build to use in IntelliJ?

**Comment by raydac** [comment]
it is o so easy to build for Idea, so that I made build and attached to the comment
[idea-mindmap.zip](https://github.com/raydac/netbeans-mmd-plugin/files/562895/idea-mindmap.zip)

**Comment by roshanq** [comment]
The zip file works, and I am able to use the feature. The list/sub-lists works good.

A couple of notes.
1) The links (external and internal) need to be in the following format

http://orgmode.org/manual/Hyperlinks.html#Hyperlinks

2) The Philosophy of your plugin and Org mode are perfect for each other. Would you be able to write an emacs package that does org mode => mind map (The format is almost similar, probably just needs a transformation)

**Comment by raydac** [comment]
I don't have experience in usage of emacs and development extensions for it

**Comment by roshanq** [comment]
Ray, fair enough.

Would you be able to fix the link bug?

links are [[ <link> ]] in org-mode

**Comment by raydac** [comment]
take a look at the version
[idea-mindmap.zip](https://github.com/raydac/netbeans-mmd-plugin/files/569913/idea-mindmap.zip)
