### ISSUE TITLE
Добавить в сущность (узел) понятие атрибут

### ISSUE THREAD

**Issue by Hoseyn76** [raydac/netbeans-mmd-plugin#3]
Добавить в сущность (узел) атрибут.
Сущность может иметь произвольное количество атрибутов.

Один атрибут - это конечный список, который имеет свою уникальную графическую визуализацию для каждого из значений.

Пример:
Приоритет = { 1, 2, 3, 4 }
Прогресс выполнения  = { 0%, 25%, 50%, 75%, 100% } (Как вариант компактной визуализации - круговая диаграмма )
Флаги = { Red, Green, Yellow, Blue, Green, Grey, White }

Пользователи должны иметь возможность сами создавать атрибуты.

Пользователь может перетащить в сущность (узел) столько атрибутов сколько ему надо.

По атрибутам потом нужна будет фильтрация.

**Comment by raydac** [comment]
аттрибуты по умолчанию присутствуют в модели и могут хранить разную функциональность, начиная с 1.2.0 появился Plugin API и можно теперь реализовывать разную требуемую специфическую функциональность самостоятельно
