### ISSUE TITLE
Question: what version of freemind do you support

### ISSUE THREAD

**Issue by ronsmits** [raydac/netbeans-mmd-plugin#31]
Exporting a mindmap to freemind opening it in either version 1.0.1 or 1.1.0-Beta shows a partially drawn mindmap with no connectors between the nodes.

**Comment by raydac** [comment]
exporter generates 1.0.1 version, are there no connectors or they just invisible because they have the same color as background?

**Comment by raydac** [comment]
I have improved free mind exporter, to make links visible
