### ISSUE TITLE
blank characters need to be trimmed

### ISSUE THREAD

**Issue by swiftech** [raydac/netbeans-mmd-plugin#33]
blank characters at head or tail of sentence always there, like "   foobar   ". In my opinion, these blanks are meaningless.

**Comment by raydac** [comment]
if you mean sentences inside mind map topics then blank chars provide way to align size of visual rectangle if user needs

**Comment by swiftech** [comment]
so a preference option may be needed to control the blank for someone like me. Usually i copy text with blank at head of tail accidentally, deleting blanks is annoying and boring, I hope this job can be handled automatically.

**Comment by raydac** [comment]
added option in configuration (in intellij, the option on the facet level)
