### ISSUE TITLE
Relative path file link between modules in IDEA plugin support

### ISSUE THREAD

**Issue by swiftech** [raydac/netbeans-mmd-plugin#35]
The file link that added to topic stored as absolute path.  It's ok for own usage, but when I share mind map file with others through VCS like SVN, the links cannot be opened even the file exists in project. Is there any solution to make it possible to support both absolute and relative path?

**Comment by raydac** [comment]
if you don't have directly disabled calculation of relative path, then plugin calculates relative path to file from the project root and saves link as relative one, it writes absolute path only if it is impossible to calculate relative path

**Comment by swiftech** [comment]
yes, but this setting is only exists in the standalone application, not in the IntelliJ IDEA plugin. Files in IDE are more likely to be shared between team members.

**Comment by raydac** [comment]
such option presented for all plugins, in intellij it is provided on the facet level
if it is impossible calculate relative path then plugin add it as absolute one and such file link marked by small yellow banner

**Comment by swiftech** [comment]
I found it and i tried, but it doesn't work for different IDEA modules. Unfortunately but is't ok, i guess it's hard to determine the path relationship between modules, thanks for your help

**Comment by raydac** [comment]
I will check, may be it is some kind of bug in work of IDEA plugin because the projec root folder should be used as root and it should work well with relative path if you make links to files in another module but of the same project, I just use usually maps on the main project level and didn't try such scenario

**Comment by raydac** [comment]
I have added flag into IJ facet t enforce use of Prject base folder instead of Modue folder so that now it is possible to make cross module file links and keep relative paths, by default it still uses Module folder as the root (as previously) to keep back compatibility
