### ISSUE TITLE
Line break doesn't wok when editing topics on Mac OS

### ISSUE THREAD

**Issue by swiftech** [raydac/netbeans-mmd-plugin#36]
Line break is not available on Mac OS either IDEA plugin or Standalone. I've tried 'shift', 'fn', 'control', 'option' and 'command' buttons, but none of them works.

OS version:
macOS Sierra 10.12.6 (16G1212)

Java version:
1.8.0_163

**Comment by raydac** [comment]
do you have sch effect with development version or with 1.4.1 release?

**Comment by swiftech** [comment]
it's version 1.4.1

**Comment by raydac** [comment]
I have reproduced the error under Mac, will investigate
