### ISSUE TITLE
Multi-select and clone nodes which has parent-child relationship makes redundant node

### ISSUE THREAD

**Issue by swiftech** [raydac/netbeans-mmd-plugin#39]
When I multi-select  node 'a' and it's child node 'b' from a parent node and paste them to another node, a redundant new 'b' node added to the another node, is it a bug or designed?

OS: Mac 10.12.6
Java: 1.8

**Comment by raydac** [comment]
could you describe step by step the operation to reproduce? may be to add screenshot

**Comment by swiftech** [comment]
Failed to upload screenshot. 
Select only one node which has children to copy and paste is ok, but not ok when you both select the node and it's children to copy and paste, duplicate children nodes will be created. I hope it's clear for you.

**Comment by raydac** [comment]
it makes copying sequentially, if you have ctrl+c for two selected nodes then they will be copied one by one with ctrl+v with their subtrees

**Comment by swiftech** [comment]
I see, thanks
