### ISSUE TITLE
NullPointerException at com.igormaznitsa.nbmindmap.nb.refactoring.elements.AbstractPlugin.processFileObject

### ISSUE THREAD

**Issue by ralphbenjamin** [raydac/netbeans-mmd-plugin#4]
https://netbeans.org/bugzilla/show_bug.cgi?id=256396

**Comment by raydac** [comment]
ok, thank you very much, looks like it is fixed in 1.1.1 version which will be published soon but I will recheck

**Comment by raydac** [comment]
fixed in 1.1.1
