### ISSUE TITLE
Version 1.4.4 for Netbeans 8.2

### ISSUE THREAD

**Issue by cunka** [raydac/netbeans-mmd-plugin#47]
The last version available through the Netbeans plugin download is 1.4.1.
So I'm looking for the latest 1.4.4 nbm file.
Do you have it available ?
Thanks

**Comment by raydac** [comment]
each release contains NBM file among pre-built bin files, [the file is NetBeans plugin](https://github.com/raydac/netbeans-mmd-plugin/releases/download/1.4.4/nb-mind-map-1.4.4.nbm), you can download it and install manually through __Tools->Plugins->Downloaded__

**Comment by cunka** [comment]
Thanks Igor
