### ISSUE TITLE
Unable to find files for Chinese characters

### ISSUE THREAD

**Issue by swiftech** [raydac/netbeans-mmd-plugin#52]
"find files for text" dialog, input Chinese words to search but found nothing 。I guess it doesn't work for any east Asian languages

**Comment by raydac** [comment]
which dialog do you mean?

**Comment by swiftech** [comment]
@raydac the "find files for text" dialog from the context menu on the left side tree

**Comment by raydac** [comment]
yes, you are right, I will investigate the case

**Comment by raydac** [comment]
I have made some fix, try pls [the snapshot version](https://github.com/raydac/netbeans-mmd-plugin/releases/tag/1.4.6-SNAPSHOT)

**Comment by swiftech** [comment]
@raydac It doesn't work in the snapshot version.

**Comment by raydac** [comment]
could you provide any test text document and string for search to reproduce?

**Comment by swiftech** [comment]
![屏幕快照 2019-04-01 下午3 39 57](https://user-images.githubusercontent.com/3277107/55311106-b203d780-5494-11e9-9b7d-d4753d30a274.jpg)
![屏幕快照 2019-04-01 下午3 41 17](https://user-images.githubusercontent.com/3277107/55311116-b9c37c00-5494-11e9-826b-9cb79c4d5c21.jpg)

**Comment by raydac** [comment]
as you can see on your screenshot, the `find` button is gray and non-activated, I have made some changes to enable search for short texts, pls try [latest snapshot](https://github.com/raydac/netbeans-mmd-plugin/releases/tag/1.4.6-SNAPSHOT)

**Comment by raydac** [comment]
@swiftech did you try snapshot version?

**Comment by swiftech** [comment]
I tried to download that version several times but all failed, it's hard to download something big from github in China. I'll try it later.

**Comment by raydac** [comment]
good point, I have added distributives without embedded JDK but they need pre-installed JDK 1.8+

**Comment by swiftech** [comment]
Fortunately, I have downloaded the JDK version, the search works for short Chinese words now, thanks for you work. One more thing, the non-jdk version failed to startup on MacBook, and I had the JDK 8 installed and $JAVA_HOME set up. I also tried to run from terminal it gives error message as follow: LSOpenURLsWithRole() failed for the application /Applications/SciaReto.app with error -10810.

**Comment by raydac** [comment]
yes, I found bug in "mac os nojre" version and replaced it by correct one
