### ISSUE TITLE
Can mindmaps be made searchable?

### ISSUE THREAD

**Issue by gansai** [raydac/netbeans-mmd-plugin#53]
Can mindmaps be made searchable?
For example, we can introduce search bar for the text and it can locate the node which has that text.

**Comment by raydac** [comment]
which version of mind map plugin do you mean? standalone, intellij idea or netbeans? or do you mean using of mind map panel component?

**Comment by gansai** [comment]
i m using intellij idea plugin.

**Comment by gansai** [comment]
can we also port this plugin to eclipse?

**Comment by raydac** [comment]
if you use intellij idea then ctrl+f should work and show search bar
![image](https://user-images.githubusercontent.com/3008810/62273143-7e868900-b445-11e9-9be1-3e79e61d1478.png)

**Comment by raydac** [comment]
I am no so strong in writing of plugins for eclipse, it doesn't use Swing so it is no so easy to port, for such cases I have developed SciaReto editor (which also has embedded PlantUml) and it can be started as external application and work with projects containing mind maps even if ide doesn't have plugins

**Comment by gansai** [comment]
Thank you @raydac for this information.
One observation is that, if we use Eclipse keymap in Intellj, then Ctrl+F does not work in mindmap.
( But I tried with Intellij default keymap and it is working as you mentioned )

**Comment by raydac** [comment]
if any problem with shortcut then you can select IDE menu item __Edit->Find->Find at Mind Map__
