### ISSUE TITLE
Loosing focus during work with mind map

### ISSUE THREAD

**Issue by mekhos** [raydac/netbeans-mmd-plugin#55]
Hi,

Every time I edit mind map or fold/unfold nodes mind map editor loose focus and I have to use mouse pointer to pick node again. It ruins my working flow.
Is it possible to fix it to keep focus constantly during editing operations? Thank you.
Environment:
IntelliJ IDEA 2019.2.1 (Ultimate Edition)
Build #IU-192.6262.58, built on August 20, 2019
Runtime version: 11.0.3+12-b304.39 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.tree.ui.experimental=false, ide.balloon.shadow.size=0, tabs.alphabetical=true
Non-Bundled Plugins: ASM Bytecode Outline, PlantUML integration, SmarterEditor, com.alayouni.ansiHighlight, com.intellij.ideolog, com.jetbrains.lightThemePreview, org.asciidoctor.intellij.asciidoc, com.perl5, nb-mind-map-idea, BashSupport, com.jetbrains.php, com.google.gct.core, zielu.gittoolbox

**Comment by raydac** [comment]
it would be good if you would describe step by step scenario to reproduce

**Comment by mekhos** [comment]
Here is the screencast:
https://drive.google.com/open?id=1OiV_-VQP8yJDcUWqEd2lsL5Oplhh8lpm
Steps to reproduce:
1. Add new topic by pressing Tab
2. Enter topic name
3. Press Enter
Actual results:
Newly entered topic has no focus and I should focus the topic again in order to  add another new topic.
Expected results:
Newly entered topic has focus and I can just press Enter again and add another new topic.

**Comment by raydac** [comment]
cool, thank you very much
is it MacOS ?

**Comment by raydac** [comment]
today I have tried reproduce the issue on two machines with such IDEA version under Windows 10, without success. Could you try reproduce the issue with  [SciaReto](https://github.com/raydac/netbeans-mmd-plugin/releases/download/1.4.6/sciareto-1.4.6-windows-x64-openjdk.zip) on the machine? it uses same component but as standalone application, to be sure that there is not any effect from IDEA

**Comment by raydac** [comment]
I could not reproduce the issue, added some code to ensure focus to edited topic, try  [SNAPSHOT version of IDEA plug-in](https://github.com/raydac/netbeans-mmd-plugin/releases/tag/1.4.7-SNAPSHOT)

**Comment by mekhos** [comment]
> I could not reproduce the issue, added some code to ensure focus to edited topic, try [SNAPSHOT version of IDEA plug-in](https://github.com/raydac/netbeans-mmd-plugin/releases/tag/1.4.7-SNAPSHOT)

This version works exactly the same. The only topic which works as expected is the main topic of mind map.

**Comment by raydac** [comment]
try please standalone SciaReto editor version with archived openjdk

**Comment by mekhos** [comment]
I've checked SciaReto and it works better. Let's divide issues with focusing on active node to a few use cases.
Case 1:
1. start editing of node (1st or 2nd level) by pressing "Ctrl+Space"
2. enter some text
3. press Enter
4. SciaReto editor keep focus on active node. Intellij IDEA editor lose focus on active node.

Case 2:
1. Unfold node children by pressing "+"
2. Fold node by pressing "-"
3. SciaReto and Intellij IDEA editors lose focus on active node.

**Comment by raydac** [comment]
I was trying to reproduce issue on several machines with similar configuration and both cases without success, also asked several users to try on their machines to reproduce such behavior, also without success... I still have no idea how to fix

**Comment by raydac** [comment]
looks like I could reproduce such behavior under 1.7 jdk in an old version of intellijidea, fixed it in 1.4.7

**Comment by raydac** [comment]
@mekhos have you try 1.4.7 version, is it still reproducible?
