### ISSUE TITLE
Unable to open project folder in 'Documents' and project disappear after restart

### ISSUE THREAD

**Issue by swiftech** [raydac/netbeans-mmd-plugin#57]
After my MacBook upgraded to Catalina(10.15) , I found 2 problems of SicaReto:
1. Open Project and navigate to the '~/Documents' folder, I can see nothing in this folder. actually there are many files and sub-folder in it. This will not happen in other folders. 

2.  create a new project or open a project somewhere, everything works fine, but after I restart the app, the project disappear, I have to re-open it every time.

I guess they are all about the new upgrade of MacOS.

Env:
MacBook Pro, Catalina(10.15) 
SciaReto 1.4.6 with java bundled

**Comment by raydac** [comment]
could you also try 1.4.7-SNAPSHOT with bundled java? to be sure  that it has same issue

**Comment by raydac** [comment]
I don't have a mac-book with such OS, as I see they changed default rights for folder access for 3th side applications, may be there are some properties to enable access per app? like as described in [manual for another app](https://nektony.com/duplicate-finder-free/folders-permission)

**Comment by swiftech** [comment]
I think you are right about the folder access control, but the system privacy panel still doesn't allow me to add a new application manually after I unlock it. Other applications like LibreOffice will request permission when accessing private folders. I guess this is what should be done in SciaReto.
<img width="442" alt="Screen Shot 2019-10-27 at 12 21 09 PM" src="https://user-images.githubusercontent.com/3277107/67629690-a22a6580-f8b4-11e9-94de-c3204b9e018e.png">

**Comment by raydac** [comment]
LibreOffice is not a Java application, as I see some changes in work with Java and access should be provided for embedded Java. Looks like a lot of applications [meet such issue with Catalina MacOs](https://youtu.be/dADUwM_4_3c)

**Comment by swiftech** [comment]
By adding Full Disk Access permission to SciaReto manually, I can see the private folders now, thanks for the instruction.
