### ISSUE TITLE
Restore the visited dir in file dialogs

### ISSUE THREAD

**Issue by swiftech** [raydac/netbeans-mmd-plugin#59]
Have you considered addding support to restore visited dir in some file dialogs. Like exporting some mind maps to other type of file, I have to select the dir where I want to save the files everytime even the targes is same, it's a little bit annoying to me. I hope the software can remember the dir path I visited last time and restore the dir next time the dialog pop up.

**Comment by raydac** [comment]
I will add such feature in 1.4.7

**Comment by raydac** [comment]
you can try 1.4.7-SNAPSHOT version
