### ISSUE TITLE
not sure if mmd issue or other

### ISSUE THREAD

**Issue by phpdan** [raydac/netbeans-mmd-plugin#6]
I just updated from Netbeans 8.0.2 to Netbeans 8.1.

Product Version: NetBeans IDE 8.1 (Build 201510222201)
Java: 1.8.0_60; Java HotSpot(TM) 64-Bit Server VM 25.60-b23
Runtime: Java(TM) SE Runtime Environment 1.8.0_60-b27
System: Linux version 3.16.0-4-amd64 running on amd64; UTF-8; en_CA (nb)

I have never install your mind map software before, so this is a fresh install. On the initial install (FYI, at the same time I chose to install Nebeans Cheat Sheets) of the plugin after Netbeans restarts I received the message:

Warning - could not install some modules: NB MindMap Editor - The module named org.netbeans.modules.java.source.compat8 was needed and not found.

Help -> Check for updates says everything up to date.
Tools -> Plugins -> Check for updates shows no new updates available.

Here is why I'm not sure if this is a Mind Map issue, under Installed plugins there is an item called "Progress API 8.0 Compatibility" which is in-active. The only other in-active item is NB MindMap Editor.

Right clicking Progress API, activate is greyed out.
Right clicking NB MindMap, activate results in:

Activation failed: Not all requested modules can be enabled: [StandardModule:com.igormaznitsa.nbmindmap jarFile: /home/(censored)/.netbeans/8.1/modules/com-igormaznitsa-nbmindmap.jar]

**Comment by raydac** [comment]
Hello
thank you for your report, take a look at [#5](https://github.com/raydac/netbeans-mmd-plugin/issues/5) please, looks it as a similar case?

**Comment by phpdan** [comment]
Different in that I did not have the mind map plugin installed with 8.0.2, it was a fresh install, non-update of the plugin into 8.1.  Similar to issue #5 I am using PHP version of Netbeans.

Uninstalled MindMap plugin. Now testNg appears in list of installed plugins, with the same status in-active and in-ability to active as API Compatibility. Uninstalled testNg, and API compatability dissapeared with it.  Chose to install MindMap plugin again, and this time when installing it, it gave me a bunch of extra java code plugins to install with it.

And yay! It works!  Good 'ol uninstall and install again. :-)

Thanks, this plugin looks great!

Daniel
