### ISSUE TITLE
SciaReto: add autosave of editors to restore content after JVM crash

### ISSUE THREAD

**Issue by swiftech** [raydac/netbeans-mmd-plugin#60]
Restart SicaReto when it crashed for some reason(for me, it's about switching input method to Chinese and it happened many times) , every changes about layout will lost,  it will restore the layout to which last time I closed the app. 
I guest this is because the layout is saved only on closing.
 BTW, could you let the tree node also restore it's fold/unfold status when starting? I think it will be great if you add this functionality.

---
sciareto 1.4.7
macOS Catalina 10.15.2
java 13.0.1

**Comment by raydac** [comment]
do you mean JVM crash? could you provide dump generated by JVM? I can contact with @BellSoft which embedded JVM I use

**Comment by swiftech** [comment]
I guess it's JVM crash, not the app, because it only happened on switching input method

**Comment by raydac** [comment]
in the case JVM generates some crash dump log file
as I see you use non-embedded jdk version, because I make embedded versions from JDK 11 as embedded one, could you try version with embedded JDK?

**Comment by swiftech** [comment]
I will try embedded version later, it will cost long time because the crash not always shows up. BTW, I think the point is, maybe it's appropriate to auto-save the layout periodically.

**Comment by raydac** [comment]
I have added auto-backup for last edit (disabled by default). If jvm crashes then last edit can be restored from backup.
![image](https://user-images.githubusercontent.com/3008810/73119457-da504b80-3f6a-11ea-95ca-4ead3e1526e7.png)
