### ISSUE TITLE
In IntelliJ a .mmd in Scrachtes opens as text-file

### ISSUE THREAD

**Issue by TobseF** [raydac/netbeans-mmd-plugin#61]
If I create `.mmd` file as Scratch, it opens as text. So I can't use the Mindmap Editor:  
Press: <kbd>ctr</kbd> + <kbd>alt</kbd> + <kbd>shift</kbd> +  <kbd>insert</kbd>
And choose: `MBMindMap`

<img width="135" alt="2020-01-27_16h26_52" src="https://user-images.githubusercontent.com/1190109/73187543-d7e42200-4121-11ea-8953-03c9bf481687.png">

<img width="294" alt="2020-01-27_16h26_08" src="https://user-images.githubusercontent.com/1190109/73187481-c438bb80-4121-11ea-8276-6b5a12baa497.png">

Scratches are used in IntelliJ to edit and sore files, which are not part of the git repsoitory. So I can create local files without sharing them. This is the way I create all my PlantUML diagrams.

**Comment by raydac** [comment]
I didn't make any special support of scratches and don't have any info about its internal API, so that I have created [ticket in their support system](https://intellij-support.jetbrains.com/hc/en-us/requests/2467019)

**Comment by raydac** [comment]
I've made fix, you can try the snapshot version

**Comment by TobseF** [comment]
Yes, thank you very much. Now its possible to create a MindMap as scratch file.
Time for the next release ? 😉

**Comment by MikhailAsadchyIDT** [comment]
Doesn't work for me :( 

https://user-images.githubusercontent.com/50206054/108594022-80e26800-7388-11eb-9f13-fdb1b133c5ab.mp4

IntelliJ IDEA 2020.3.2 (Ultimate Edition)
Build #IU-203.7148.57, built on January 26, 2021

@raydac

**Comment by raydac** [comment]
@MikhailAsadchyIDT 
I have tried it under 2021 EAP and looks working without problems, in downloaded Ultimate 2020.3.2 I can reproduce the issue only if I create scrath throup popup menu for "Scratches" folder, if I create mind map through popup "Scratches and Consoles"->"New" then mind map shown well. Looks like that Intellij team fixed the issue in 2021, in your case you can select in popup menu for the file "Change langiage (NBMindMap) to.." and select the same NBMindMap from the list and it will fix work of IDE

**Comment by MikhailAsadchyIDT** [comment]
Thank you. That works to me.
