### ISSUE TITLE
Editing colors doesn't (auto) save

### ISSUE THREAD

**Issue by sopgreg** [raydac/netbeans-mmd-plugin#63]
### Plugin

IDEA Mind Map 1.4.7

### Bug Description

When editing a color on a node, the mmd is not saved until another node change happens, like
- insertion/deletion of a node
- text edit on a node

When colors are edited and IntelliJ IDEA is closed then all changes are lost.

**Comment by raydac** [comment]
I have fixed, you can try the snapshot version

**Comment by sopgreg** [comment]
Works now, thanks a lot!
