### ISSUE TITLE
Performance of rendering is not good

### ISSUE THREAD

**Issue by swiftech** [raydac/netbeans-mmd-plugin#64]
The performance of rendering mindmap is not good, when I scroll the viewport, the mindmap goes not smoothly, I can see the frame missing. for the plantuml diagram, the situation is even worse. Would you consider to do some profiling and make it better?

SciaReto: 1.4.7
MacOS: 10.15.3
Java: 11.0.5

**Comment by raydac** [comment]
I don't have Mac (only emulator of it) and didn't see such behavior, under Linux and Windows it works fast enough
could you try to start sciareto jar with system flag -Dsun.java2d.opengl=true
also speed can be affected by value in Preferences->Render quality, which value do you use?

**Comment by swiftech** [comment]
Change Render quality from `QUALITY` to `SPEED` doesn't work, still slow. 
And I tried to launch with opengl like:  `/usr/bin/java -jar /Applications/SciaReto.app/Contents/MacOS/scia-reto-1.4.7.jar -Dsun.java2d.opengl=true`

but unfortunately, everything disappear :
<img width="1256" alt="Screen Shot 2020-03-11 at 4 20 06 PM" src="https://user-images.githubusercontent.com/3277107/76396748-bcbd3100-63b4-11ea-989b-2345c520bd31.png">

**Comment by raydac** [comment]
could you try version with embedded JRE? do you work with very big mind map or such behavior even with small mind maps?

**Comment by swiftech** [comment]
1. the command `/usr/bin/java -Dsun.java2d.opengl=true -jar /Applications/SciaReto.app/Contents/MacOS/scia-reto-1.4.7.jar` starts fine, but still low performance.
2. Re-download embedded version and now the command is `/Applications/SciaReto.app/Contents/MacOS/jre/bin/java -jar /Applications/SciaReto.app/Contents/MacOS/scia-reto-1.4.7.jar` but everything still the same.
3. I don't consider my mind map as very big, because most of them contains about 20-30 nodes, for the plantuml diagram, with 20-30 elements scrolls very slow.
4. One thing I noticed is that the smaller plantuml diagram viewport is, the more smoothly scrolling will be, I think the mind map is the same, just not so obvious.

**Comment by raydac** [comment]
interesting that I can't reproduce slowness even under virtualbox, when you detected the slowness? as I see you use sciareto for some time and does it have such issue since start of use?

**Comment by swiftech** [comment]
Actually it always act like that since I started to use on Mac, I knew maybe it's not easy to fix and it was not too annoy at the beginning, but it's  unbearable recently because I use plantuml more and more.

**Comment by swiftech** [comment]
May be I will take some time to help diagnosis on my own, if I have enough time to learn something about rendering and  performance profiling.

**Comment by raydac** [comment]
try 1.4.8-SNAPSHOT, I had too high quality for image rendering in plantuml editor, now it takes parameter from render quality option

**Comment by swiftech** [comment]
tried 1.4.8-SNAPSHOT, the plantuml digram scrolls smoothly now. 
but still one issue, the moving behaviour  is a little different between using scroll bar and using Mac's TrackPad,  the scroll bar is ok,  but using track pad, there is a tiny shaking . I'm not sure it's ok or not on other laptop's track pad because I have only Mac laptop to try.

**Comment by raydac** [comment]
could you make some small video? because I can't reproduce under macos emulator

**Comment by swiftech** [comment]
![Screen-Recording-2020-03-14-at-1](https://user-images.githubusercontent.com/3277107/76684980-2191b900-664b-11ea-9e8e-0c289e711670.gif)

*.mov or *.mp3 is not allowed to upload, so the gif
