### ISSUE TITLE
The ctrl + s shortcut should save single opened doc

### ISSUE THREAD

**Issue by swiftech** [raydac/netbeans-mmd-plugin#65]
The ctrl + s shortcut of SciaReto saves all the opened docs, but I think it should only save current opened doc.

**Comment by raydac** [comment]
Scia Reto copies short cuts from standard IDEs (Intellij and NetBeans) and in both of them Ctrl+S means "Save all"

**Comment by swiftech** [comment]
Yes, it is in IDEs. But  in IDEs, files are strong related because most of time you have to save them all to let them build correctly, I think that's why IDEs take ctrl+s as "save all". But for SicaReto, which is similar to text editors like Sublime or Atom, files opened usually have no relations at all, so I think "Save" is used more frequently than the "Save all" in this situation.

**Comment by raydac** [comment]
good idea, I will think how to split `save` and `save all` like in text editors

**Comment by raydac** [comment]
now Ctrl+S saves one document and Ctrl+Shift+S saved all documents

**Comment by swiftech** [comment]
I don't see this change in 1.4.9-snapshot on MacOS

<img width="229" alt="Screen Shot 2020-05-16 at 11 20 56 AM" src="https://user-images.githubusercontent.com/3277107/82109300-616a3f00-9767-11ea-8133-997038053634.png">
