### ISSUE TITLE
Import from xmind2020 doesen't work

### ISSUE THREAD

**Issue by dzailz** [raydac/netbeans-mmd-plugin#67]
import from xmind2020 file now looks this
![image](https://user-images.githubusercontent.com/51898657/84576569-63530c80-adbe-11ea-923f-634c015bf3d3.png)
As I can see, you used the content.xml file to import, but I think that now they use the “content” file in json format

**Comment by raydac** [comment]
I made improvements in XMind importer, you can try 1.4.9-SNAPSHOT
