### ISSUE TITLE
Plugin incompatible with latest WebStorm EAP

### ISSUE THREAD

**Issue by jvanoostveen** [raydac/netbeans-mmd-plugin#70]
Not sure who is to blame, but when running the WebStorm EAP, this plugin causes the editor to not be able to open any file. As I am running the early access versions, I expect things to break, but most of the time, when a plugin is not compatible it just won't load it and keeping the rest of the application intact. This specific incompatibility breaks core functionality for the editor 🤕.

Link to the JetBrains ticket: https://youtrack.jetbrains.com/issue/WEB-46270

**Comment by jvanoostveen** [comment]
Additional version information:
WebStorm 2020.2 EAP
Build #WS-202.5958.22, built on June 24, 2020
WebStorm EAP User
Runtime version: 11.0.7+10-b944.13 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: documentation.show.toolbar=true, js.debugger.webconsole=false
Non-Bundled Plugins: com.dubreuia, AceJump, PlantUML integration, com.github.leomillon.uuidgenerator, org.intellij.plugins.postcss, com.j92.current-date-generator, de.netnexus.camelcaseplugin, com.microsoft.vso.idea, zielu.gittoolbox, org.sylfra.idea.plugins.linessorter, org.turbanov.run.configuration.as.action

**Comment by raydac** [comment]
the bug has been [fixed in 1.4.9](https://github.com/raydac/netbeans-mmd-plugin/issues/69) but the version is still waiting for moderation on Intellij portal, you can also just load the plugin from releases and install manually

**Comment by jvanoostveen** [comment]
Ah great. I already saw an pending update, but that might have been unrelated. Thanks for your quick response (and fix already in the pipeline).
