### ISSUE TITLE
Can not open basic Freemind 1.0.1 file

### ISSUE THREAD

**Issue by albilu** [raydac/netbeans-mmd-plugin#71]
Hello,
Can not open a simple Freemind file. Is it supported or not?
Same for a Mindmap create from NB mind map, it is not openning in Freemind
![mindmap](https://user-images.githubusercontent.com/35330562/86092576-f7ef8700-baad-11ea-999f-0e5e9602bd57.PNG)

**Comment by raydac** [comment]
it can't directly open save FreeMind files but supports import-export for FreeMind, if you have problems with some FreeMind file then attach it to the issue

**Comment by albilu** [comment]
Great thanks you.
