### ISSUE TITLE
SciaReto will be stuck with inputing emoji

### ISSUE THREAD

**Issue by swiftech** [raydac/netbeans-mmd-plugin#72]
As the gif showed, it is stuck after emoji character selected.
and, this fix seems still not working when stuck and force closed:
https://github.com/raydac/netbeans-mmd-plugin/issues/60

MacOS 10.15.5
SciaReto 1.4.9
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/3277107/87222459-5d911c80-c3a6-11ea-8a7d-a05958eac0ff.gif)

**Comment by raydac** [comment]
what is the software which provides emoji?

**Comment by raydac** [comment]
could you attach some Chinese text which hangs editor during enter?

**Comment by swiftech** [comment]
The software is the MacOS's standard Chinese input source, if you input a Chinese word which has the same meaning with one emoji, it will show this emoji in the list and let you choose.  I have tried no matter what emoji selected, the SciaReto will hang and CPU is very high.

**Comment by swiftech** [comment]
For example, if I want to input "car" in Chinese, I just type "qiche", the Chinese word “汽车” and emoji car will both show in the list. at that time, input number 1 will choose Chinese word “汽车” and it's ok, input number 2 will choose emoji car but this  makes the app stuck.

**Comment by raydac** [comment]
looks like that it is known [bug on Java level](https://bugs.openjdk.java.net/browse/JDK-8148555)
could you try 1.4.10-SNAPSHOT with embedded JDK?

**Comment by swiftech** [comment]
Yes, this snapshot version won't hang ,but only a blank shows instead of emoji image after input. Is this the actual result your fix want to get?

<img width="239" alt="Screen Shot 2020-07-28 at 11 21 00 AM" src="https://user-images.githubusercontent.com/3277107/88615458-929ab000-d0c4-11ea-9c78-6f8002295579.png">

**Comment by raydac** [comment]
try to change `Mind map topic text font` in Preferences, may be you have currently selected font which doesn't have emoji icons

**Comment by swiftech** [comment]
This is my font config:
<img width="346" alt="Screen Shot 2020-07-28 at 7 57 45 PM" src="https://user-images.githubusercontent.com/3277107/88662603-c3063c80-d10c-11ea-8400-7e2a49a4f159.png">

I have tried to change to some other fonts, but still see blank. I not sure about how the font renders, but I don't think it is the reason.

**Comment by raydac** [comment]
there should be some specific font which supports emoji, I saw even some [free fonts from google](https://www.google.com/get/noto/) with support of such stuff but may be Java just doesn't support rendering of such font out of the box, will try to find in network some solutions

**Comment by raydac** [comment]
1.14.10 works well?

**Comment by swiftech** [comment]
Still not works, and this problem also appears in the note editor. But I noticed that the emoji shows at the window bar correctly.
<img width="394" alt="Screen Shot 2021-01-01 at 6 38 51 PM" src="https://user-images.githubusercontent.com/3277107/103437273-a2648480-4c60-11eb-8679-8d94e86df552.png">
