### ISSUE TITLE
The indent behavior works  inconsistent in the puml editor 

### ISSUE THREAD

**Issue by swiftech** [raydac/netbeans-mmd-plugin#73]
If I select multiple lines and hit 'Tab', all these lines will be indented, it's fine, but if select only one line and hit 'Tab', this line will be replaced by a 'tab' character , I think the behavior should be the same with previous.

SciaRetor v 1.4.10-SNAPSHOT

**Comment by swiftech** [comment]
Besides, the 'tab' character occupies 5 letters, it's unusual, 2, 4 or 8 are usually used. Providing a setting option if possible is very nice.

**Comment by raydac** [comment]
fixed in 1.4.11
