### ISSUE TITLE
Changing letter case of file name doesn't work

### ISSUE THREAD

**Issue by swiftech** [raydac/netbeans-mmd-plugin#74]
If I have a file names 'FOOBAR.puml', I try to change it's name to 'foobar.puml', the file name in the tree will be changed but the actual file name still in upper case, the file name will be reverted after I reload tree or restart the app.

Version: 1.4.10
OS: Mac

**Comment by raydac** [comment]
try 1.4.10-SNAPSHOT

**Comment by swiftech** [comment]
It works on latest 1.4.10-SNAPSHOT
