### ISSUE TITLE
[REQUEST] Add plugin to new plugin repo for Apache netbeans.

### ISSUE THREAD

**Issue by Borwe** [raydac/netbeans-mmd-plugin#79]
Requesting if possible to add plugin to new plugin repo for Apache netbeans at https://plugins.netbeans.apache.org/ would make it more easier for users to access.

**Comment by raydac** [comment]
now they need NBM published in maven central, I will try it in next release

**Comment by raydac** [comment]
I started publishing the NetBeans pkugin in Maven Central since 1.4.11 so that it will be accessible in NB as only it will be approved on NB portal
