### ISSUE TITLE
"Find files for test" can't match topics correctly in some cases

### ISSUE THREAD

**Issue by swiftech** [raydac/netbeans-mmd-plugin#83]
OS: macOS Catalina
Version: 1.4.11

Suppose there is a topic in mmd file contains string with '_' like "hello_world", 
I can find this mmd file by searching with "_world" or "_w" or "_",
but I can't find it by searching with  "hello_world" or "hello_" or "o_".

**Comment by raydac** [comment]
describe process step by step please

**Comment by raydac** [comment]
ok, I have reproduced it

**Comment by raydac** [comment]
@swiftech you can try snapshot with fix

**Comment by swiftech** [comment]
It works fine in the latest snapshot.

**Comment by raydac** [comment]
great, thanks a lot!
