### ISSUE TITLE
"Find files for text" does not include file name

### ISSUE THREAD

**Issue by swiftech** [raydac/netbeans-mmd-plugin#85]
version 1.4.12
OS: mac Catalina 10.15.7

I noticed that the "Find files for text" only searches in content of files but not the file name. for example:
if a file names "scia reto.mmd' but "scia" or "reto" does not exist in the content of file, I can't find this file by given keyword "scia" or "reto".

I know there is a "Got to file" dialog can search files by keyword, but  I usually don't remember whether the keyword is in the file name or file content, so I have to do the search twice very often.

**Comment by raydac** [comment]
good idea, I will improve search

**Comment by raydac** [comment]
you can try snapshot
