### ISSUE TITLE
Waning when launching the SciaReto 1.5 SNAPSHOT

### ISSUE THREAD

**Issue by swiftech** [raydac/netbeans-mmd-plugin#89]
After I updated to the latest snapshot, I got following warning when I launch the app. In the app, the Look and Feel was changed to Nimbus automatically.

<img width="558" alt="Screen Shot 2021-12-04 at 1 11 55 PM" src="https://user-images.githubusercontent.com/3277107/144698089-69f15b2e-da97-4d28-80b6-f523c0e75073.png">

But what's fortunate is the emoji in the topic shows, I don't known whether  it is related to the waning.

<img width="301" alt="Screen Shot 2021-12-04 at 1 17 35 PM" src="https://user-images.githubusercontent.com/3277107/144698244-71ed5303-ff3a-488a-b6fe-1c9f0e54d675.png">

Version: sciareto-1.5.0-SNAPSHOT-macos-jdk-amd64
OS: macOS Catalina

**Comment by raydac** [comment]
looks like that Java has fixed work with emoji in version 17
I have fixed the warning  in snapshot
