### ISSUE TITLE
How to move the map in all directions instead of only in the middle?

### ISSUE THREAD

**Issue by actforjason** [raydac/netbeans-mmd-plugin#97]

**Comment by raydac** [comment]
if the size of a map  is less than field where it is rendered then the map is rendered in the center, else you can use scrollbars to scroll it (on my notebook touch-pad scroll also works)

**Comment by raydac** [comment]
what do you mean as background screen?

**Comment by actforjason** [comment]
Mouse left click to drag the background screen
![image](https://user-images.githubusercontent.com/57058325/161244290-7f6d2bf2-fec7-40c1-b9e2-b60a1f8040b3.png)
